name: praktik-new
recipe: wordpress
config:
  webroot: .
  proxy:
    appserver:
      - praktik-new.lndo.site
  portforward:
    appserver:
      - '8080:80'
  services:
    pma:
      type: phpmyadmin
      portforward: false
      hosts:
        - database